-- Flash
-- local flash = require("flash")
-- vim.keymap.set("n", "<leader>jj", flash.jump, { desc = "Flash jump" })
-- vim.keymap.set("n", "<leader>jt", flash.treesitter, { desc = "Flash treesitter" })
-- vim.keymap.set("n", "<leader>js", flash.treesitter_search, { desc = "Flash treesitter search" })
-- vim.keymap.set("n", "<leader>jh", flash.toggle, { desc = "Flash toggle" })
