local M = {}

M.icons = {
	Text = "󰉿",

	Value = "󰎠",
	Color = "󰏘",
	File = "󰈙",
	Folder = "󰉋",
	Module = "",
	Namespace = "",
	Package = "",
	Interface = "",
	Trait = "",
	Class = "",
	Struct = "󰙅",
	Field = "󰜢",
	Property = "󰜢",
	Method = "m",
	Constructor = "",
	Snippet = "",
	Copilot = "",
	Function = "󰊕",
	Variable = "󰀫",
	Boolean = "󰨙",
	Array = "󰅪",
	Object = "󰘦",
	String = "󰀬",
	Number = "󰎠",
	Enum = "",
	EnumMember = "",
	TypeParameter = "",
	Key = "󰌋",
	Constant = "󰏿",
	Null = "󰟢",
	Unit = "󰑭",
	Operator = "󰆕",
	Reference = "",
	Keyword = "",
	Event = "",
}

M.colors = {
	Text = "turquoise",
	Value = "orange",
	Color = "yellow",
	File = "blue",
	Folder = "blue",
	Module = "green",
	Namespace = "green",
	Package = "green",
	Interface = "yellow",
	Trait = "yellow",
	Class = "green",
	Struct = "green",
	Field = "purple",
	Property = "purple",
	Method = "purple",
	Constructor = "yellow",
	Snippet = "red",
	Copilot = "red",
	Function = "blue",
	Variable = "purple",
	Boolean = "orange",
	Array = "orange",
	Object = "orange",
	String = "orange",
	Number = "orange",
	Enum = "yellow",
	EnumMember = "yellow",
	TypeParameter = "yellow",
	Key = "pink",
	Constant = "purple",
	Null = "purple",
	Unit = "yellow",
	Operator = "yellow",
	Reference = "red",
	Keyword = "red",
	Event = "red",
}

return M

-- Struct = "",
-- Module = " ",
-- Namespace = "󰌗 ",
-- Object = "󰅩 ",
-- Struct = "󰌗 ",
-- Field = "",
-- Class = "󰠱",
-- Module = "",
-- EnumMember = "",
-- Field = "",
-- Variable = "",
-- Interface = "",
-- Module = "",
-- Property = "",
-- Unit = "",
-- Value = "",
-- Keyword = "",
-- Snippet = "",
-- Color = "",
-- File = "",
-- Reference = "",
-- Folder = "",
-- EnumMember = "",
-- Constant = "",
-- Struct = "",
-- Event = "",
-- Operator = "",
-- Array = "",
-- Boolean = "",
-- Constant = "",
-- Enum = "",
-- EnumMember = "",
-- Null = "ﳠ",
-- Number = "",
-- Reference = "",
-- String = "",
-- Array = " ",
-- Control = " ",
-- Collapsed = " ",
-- Keyword = " ",
-- Namespace = "󰦮 ",
-- Null = " ",
-- Property = " ",
-- Reference = " ",
-- String = " ",
-- Struct = "󰆼 ",
-- TabNine = "󰏚 ",

-- local vscode_icons = {
-- 	File = " ",
-- 	Module = " ",
-- 	Namespace = " ",
-- 	Package = " ",
-- 	Class = " ",
-- 	Method = " ",
-- 	Property = " ",
-- 	Field = " ",
-- 	Constructor = " ",
-- 	Enum = " ",
-- 	Interface = " ",
-- 	Function = " ",
-- 	Variable = " ",
-- 	Constant = " ",
-- 	String = " ",
-- 	Number = " ",
-- 	Boolean = " ",
-- 	Array = " ",
-- 	Object = " ",
-- 	Key = " ",
-- 	Null = " ",
-- 	EnumMember = " ",
-- 	Struct = " ",
-- 	Event = " ",
-- 	Operator = " ",
-- 	TypeParameter = " ",
-- }

--[[
--
	File = { icon = '󰈔', hl = 'Identifier' },
      Module = { icon = '󰆧', hl = 'Include' },
      Namespace = { icon = '󰅪', hl = 'Include' },
      Package = { icon = '󰏗', hl = 'Include' },
      Class = { icon = '𝓒', hl = 'Type' },
      Method = { icon = 'ƒ', hl = 'Function' },
      Property = { icon = '', hl = 'Identifier' },
      Field = { icon = '󰆨', hl = 'Identifier' },
      Constructor = { icon = '', hl = 'Special' },
      Enum = { icon = 'ℰ', hl = 'Type' },
      Interface = { icon = '󰜰', hl = 'Type' },
      Function = { icon = '', hl = 'Function' },
      Variable = { icon = '', hl = 'Constant' },
      Constant = { icon = '', hl = 'Constant' },
      String = { icon = '𝓐', hl = 'String' },
      Number = { icon = '#', hl = 'Number' },
      Boolean = { icon = '⊨', hl = 'Boolean' },
      Array = { icon = '󰅪', hl = 'Constant' },
      Object = { icon = '⦿', hl = 'Type' },
      Key = { icon = '🔐', hl = 'Type' },
      Null = { icon = 'NULL', hl = 'Type' },
      EnumMember = { icon = '', hl = 'Identifier' },
      Struct = { icon = '𝓢', hl = 'Structure' },
      Event = { icon = '🗲', hl = 'Type' },
      Operator = { icon = '+', hl = 'Identifier' },
      TypeParameter = { icon = '𝙏', hl = 'Identifier' },
      Component = { icon = '󰅴', hl = 'Function' },
      Fragment = { icon = '󰅴', hl = 'Constant' },
      TypeAlias = { icon = ' ', hl = 'Type' },
      Parameter = { icon = ' ', hl = 'Identifier' },
      StaticMethod = { icon = ' ', hl = 'Function' },
      Macro = { icon = ' ', hl = 'Function' },
--]]
--]]
